---
- name: Ensure NGINX is installed
  apt:
    name: "{{ nginx_package }}"
    state: present

- name: Copy NGINX configuration
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_dest }}"
  notify: restart nginx

- name: Ensure NGINX conf.d directory exists
  file:
    path: "{{ nginx_conf_dir }}"
    state: directory

- name: Copy web configuration for NGINX
  copy:
    src: "{{ nginx_web_conf_src }}"
    dest: "{{ nginx_web_conf_dest }}"
  notify: restart nginx

- name: Start NGINX service
  service:
    name: "{{ nginx_service_name }}"
    state: started
    enabled: yes
