---
- name: Install Docker
  hosts: all_hosts
  become: true
  vars:
    docker_sdk_for_python_install: true
    docker_compose_install: true
  roles:
    - common

- name: Deploy API and Database on localhost
  hosts: apiserver
  become: yes
  vars:
    sync_repo: true
  vars_files:
    - vault.yml
  roles:
    - api
    - db

- name: Deploy Web Application and Configure NGINX on remotehost
  hosts: webserver
  become: yes
  vars:
    sync_repo: false
  vars_files:
    - vault.yml
  roles:
    - web
    - nginx
