---
- name: Set up code
  include_tasks: set-up-code.yml
  when: sync_repo
  
- name: Build image
  include_tasks: build-image.yml

- name: Check if the api_service container exists
  ansible.builtin.command:
    cmd: docker ps -a -q -f name={{ api_container_name }}
  register: container_id
  ignore_errors: true

- name: Stop the existing api_service container
  ansible.builtin.command:
    cmd: docker stop {{ container_id.stdout }}
  when: container_id.stdout != ""
  ignore_errors: true

- name: Remove the existing api_service container
  ansible.builtin.command:
    cmd: docker rm {{ container_id.stdout }}
  when: container_id.stdout != ""
  ignore_errors: true

- name: Deploy api service container
  community.docker.docker_container:
    name: "{{ api_container_name }}"
    image: "{{ api_image }}:{{ api_image_tag }}"
    env_file: "{{ env_file_path }}"
    ports:
      - "{{ api_port }}:8000"
    state: started

- name: Show logs of the api service container
  ansible.builtin.command:
    cmd: docker logs {{ api_container_name }}
  register: container_logs

- name: Display container logs
  debug:
    var: container_logs.stdout
