- name: Check if the destination directory already exists
  ansible.builtin.stat:
    path: "{{ api_clone_dest }}"
  register: git_clone_dir

- name: Clone api repository if it does not exist
  ansible.builtin.git:
    repo: "{{ api_git_credentials }}"
    dest: "{{ api_clone_dest }}"
    version: "{{ api_repo_version }}"
    force: yes
  when: not git_clone_dir.stat.exists


- name: Pull the latest changes 
  ansible.builtin.command:
    cmd: "git pull origin {{ api_repo_version }}"
    chdir: "{{ api_clone_dest }}"
  when: git_clone_dir.stat.exists

- name: Create .env file with variables
  copy:
    dest: "{{ api_clone_dest }}/users/.env"
    content: |
      {% for env_var in env_vars %}
      {{ env_var.key }}={{ env_var.value }}
      {% endfor %}
    mode: '0644'