---
api_repo_url : "https://github.com/descent1511/vdt2024-api-nodejs"

api_container_name: "api_service"

api_image: "my_api_app"

api_image_tag: "latest"

api_port: 8000

git_credentials: "https://{{ git_username }}:{{ git_password }}@{{ api_repo_url | regex_replace('^https://', '') }}"

api_repo_version: "main"

docker_user: descent
