---
- name: Install docker dependencies
  ansible.builtin.apt:
    name: "{{ docker_dependencies }}"
    update_cache: yes

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add docker gpg key
  ansible.builtin.apt_key:
    url: "{{ docker_gpg_url }}"
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: Add docker repository
  ansible.builtin.apt_repository:
    filename: "{{ docker_repo_filename }}"
    repo: "{{ docker_repo_options }}"
    state: present

- name: Install docker engine
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    update_cache: yes
