- name: Install Git 
  ansible.builtin.apt:
    name: git
    state: present

- name: Set Git user name
  command: git config --global user.name "{{ git_username }}"
  when: git_version.changed or git_version.rc == 0

- name: Set Git user email
  command: git config --global user.email "{{ git_email }}"
  when: git_version.changed or git_version.rc == 0

- name: Configure Git to use credential store
  command: git config --global credential.helper store
  when: git_version.changed or git_version.rc == 0

- name: Store Git credentials
  copy:
    dest: ~/.git-credentials
    content: "https://{{ git_username }}:{{ git_password }}@github.com"
  when: git_version.changed or git_version.rc == 0
