---
- name: Check if Git is installed
  command: git --version
  register: git_installed
  ignore_errors: true

- name: Install Git if not present
  apt:
    name: git
    state: present
  when: git_installed.failed
